### ISSUE TITLE
TypeError: Cannot read property 'randomPrivateKey' of undefined

### ISSUE THREAD

**Issue by shamtroon** [espritblock/react-native-eos#8]
Hey, 
I want to generate new key-pairs of Eos Keys, using 'react-native-eos', but whenever I import package and call any function of it, it causes error. Now I am using 'randomPrivateKey, so I am facing  

> TypeError: Cannot read property 'randomPrivateKey' of undefined

**Comment by srmcatee1110** [comment]
Hi @shamtroon 

Can you paste your code here?

**Comment by shamtroon** [comment]
Thanks @srmcatee1110  for reply, I solved this issue

**Comment by Prathyusha-acc** [comment]
const secp =require("ethereum-cryptography/secp256k1");
const {toHex} = require("ethereum-cryptography/utils");

const privateKey = secp.utils.randomPrivateKey();
console.log("privateKey :",toHex(privateKey));

This is my code for random private key generation.
#Getting error as
const privateKey = secp.utils.randomPrivateKey();
                                             ^
TypeError: Cannot read properties of undefined (reading 'randomPrivateKey')
solve this anyone.
